platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true
  project: GatebluServiceTray.sln

before_build:
  - nuget restore

artifacts:
  - path: MyProject\bin\$(configuration)
    name: GatebluServiceTray

deploy:
  - provider: S3
    access_key_id: AKIAIT4X4NDGM2WVL6VA
    secret_access_key:
      secure: J01/MZX00MKgxnFXoyiqoHSSwZbccuEfIUhw9yqRErCO0WWv/m3qDAqLe7RaN/E5
    bucket: gateblu
    folder:
    artifact:
    set_public: false
